source "https://rubygems.org"

gem "rails", "~> 8.1.4"
gem "pg", "~> 1.7"
gem "activerecord-postgis-adapter", "~> 11.0"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "kamal", require: false
gem "thruster", require: false
gem "image_processing", "~> 2.2"
gem "rack-cors"
gem "bcrypt", "~> 3.1"
gem "jwt", "~> 3.3"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "dotenv-rails", "~> 3.1"
end
